name: Build

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ github.token }}
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'yarn'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
        include-prerelease: true
    - name: Build affected
      run: |
        corepack enable
        make templates -B
        make base_ref=origin/main
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        flags: unittests
        name: ${{ github.ref_name }}
        override_branch: ${{ github.ref_name }}
        # commit_parent: ${{ github.sha }}
