# This is a basic workflow to help you get started with Actions

name: Merge

on:
  push:
    branches: [ main ]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Create build artifacts
        run: make artifacts
        env:
          base_ref: origin/${{ github.base_ref }}
      - name: Set variables
        run: |
          VER=$(cat RELEASE_VERSION)
          echo "RELEASE_VERSION=$VER" >> $GITHUB_ENV
      - name: Create Release
        env:
          ARTIFACTS_DIR: ./dist/artifacts
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          hub release create $(find "$(ARTIFACTS_DIR)" -type d -maxdepth 1 ! -name "artifacts" -printf "-a %p ") -m "$RELEASE_VERSION" -m "$COMMIT_MESSAGE" "$RELEASE_VERSION"
      - name: Update Versions
        run: make version