name: Pull Request

on:
  pull_request:
    branches: [ main,develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN_KILLIAN }}
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'yarn'
    - name: Build affected
      env:
        BASE_REF: origin/${{ github.base_ref }}
        HEAD_REF: origin/${{ github.head_ref }}
      run: |
        git config --global user.email "hale.killian@gmail.com"
        git config --global user.name "Killian Hale"
        corepack enable
        make format base_ref=$BASE_REF commit=true commit-branch=$HEAD_REF
        make templates -B
        make base_ref=$BASE_REF
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        flags: unittests
        name: ${{ github.head_ref }}
        commit_parent: ${{ github.sha }}
