# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hub CLI
        run: |
          wget -q -O- \
          https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz  | \
          tar xz --strip-components=1 --wildcards '*/bin/hub'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Get release assets
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          hub release download "$TAG_NAME" -i "*.zip"
          for f in $$(find . -type f -name "*.zip"); do unzip -q $$f; done;