name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hub CLI
        run: |
          wget -q -O- \
          https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz  | \
          tar xz --strip-components=1 --wildcards '*/bin/hub'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: Get release assets
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_KILLIAN}}
          TAG_NAME: ${{ github.event.release.tag_name }}
          PACKAGES_DIST_DIR: ./dist/packages
        run: |
          echo 📩 Fetching release assets...
          hub release download "$TAG_NAME" -i "*.zip";
          
          for f in $(find . -type f -name "*.zip"); do echo 📦 Unzipping $f...; unzip -q $f; done;
          echo 
          for f in $(find "$PACKAGES_DIST_DIR" -type d -maxdepth 1 ! -name "packages"); do echo 📡 Publishing $f to npm...; npm publish $f --access public; echo; done;

          RELEASE_CONTENTS=$(find "$PACKAGES_DIST_DIR" -type d -maxdepth 1 ! -name "packages"  -printf "- [%p](https://www.npmjs.com/package/@nx-boat-tools/%p/$TAG_NAME)\n")
          echo "RELEASE_CONTENTS_MESSAGE=$VER" >> $GITHUB_ENV

      # - uses: juztcode/gitter-github-action@v1
      #   with:
      #     room-id: ${{ secrets.GITTER_ROOM_COMMUNITY }}
      #     token: ${{ secrets.GITTER_TOKEN_KILLIAN }}
      #     text: |
      #     ## 🚢 Version ${{ github.event.release.tag_name }} was just released!\n
      #     This release contains the following npm packages:\n
      #     ${{ env.RELEASE_CONTENTS_MESSAGE }}\n
      #     \n
      #     [🔗   View the changes on GitHub](${{ github.event.release.html_url }})\n